[features]
seeds = false
skip-lint = false
[programs.localnet]
sea_nn = "EUpVs4QcQwmLGSWbHieb5HxuBegxYCyYd6CyyVix9g6M"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/codespace/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
